# This file created by conda-build 3.17.6
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/graphite2-1.3.13-on-linux_canary, last modified Thu Jan 10 21:26:51 2019
# ------------------------------------------------

package:
    name: graphite2
    version: 1.3.13
source:
    sha256: dd63e169b0d3cf954b397c122551ab9343e0696fb2045e1b326db0202d875f06
    url: https://github.com/silnrsi/graphite/releases/download/1.3.13/graphite2-1.3.13.tgz
build:
    number: '0'
    run_exports:
        - graphite2 >=1.3.13,<2.0a0
    string: h23475e2_0
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_6
        - bzip2 1.0.6 h14c3975_5
        - ca-certificates 2018.03.07 0
        - cmake 3.12.2 h52cb24c_0
        - expat 2.2.6 he6710b0_0
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_6
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_6
        - krb5 1.16.1 h173b8e3_7
        - libcurl 7.63.0 h20c2e04_1000
        - libedit 3.1.20170329 h6b74fdf_2
        - libgcc-ng 8.2.0 hdf63c60_1
        - libssh2 1.8.0 h1ba5d50_4
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - make 4.2.1 h1bed415_1
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1a h7b6447c_0
        - rhash 1.3.6 h1ba5d50_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    host:
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
about:
    home: http://graphite.sil.org/
    license: LGPLv2
    license_file: COPYING
    summary: A "smart font" system that handles the complexities of lesser-known languages
        of the world.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mingwandroid
        - ocefpaf
        - pkgw
