# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/r-base-3.6.1-on-linux_64, last modified Thu Oct  3 17:39:00 2019
# ------------------------------------------------

package:
    name: r-base
    version: 3.6.1
source:
    patches:
        - 0001-Darwin-Remove-unicode-elipsis-character-from-grDevic.patch
        - 0002-Fix-trio-config.h-include-depth-issue.patch
        - 0003-Win32-Do-not-link-static-libgcc.patch
        - 0004-Win32-Extend-sqrt-NA_real_-hack-to-all-GCC-versions.patch
        - 0005-Win32-Prevent-conversion-of-R_ARCH-to-abs-Windows-pa.patch
        - 0006-Darwin-Avoid-setting-DYLD_FALLBACK_LIBRARY_PATH.patch
        - 0007-Use-AC_SEARCH_LIBS-to-search-for-ncursesw-then-ncurs.patch
        - 0008-Linux-Do-not-modify-LD_LIBRARY_PATH.patch
        - 0009-macOS-include-cairo.h-not-cairo-xlib.h.patch
        - 0010-javareconf-Do-not-fail-on-compile-fail.patch
        - 0011-Revert-part-of-9b818c6dc00143ff18775a4015a3f43b5196f.patch
        - 0012-javareconf-macOS-Continue-to-allow-system-Java-lt-9-.patch
        - 0013-Allow-rpath-in-tcltk-dylib-LC_LOAD_DYLIB-command.patch
        - 0014-Add-luuid-to-X_PRE_LIBS.patch
        - 0015-link-Xt-to-uuid.patch
        - 0016-Mimic-OpenBLAS-when-making-reference-Rblas-and-Rlapa.patch
        - 0017-Foribly-remove-then-forcibly-mv-in-javareconf.in.patch
        - 0018-Use-LAPACK_LDFLAGS-in-Rlapack_la_LIBADD.patch
    sha256: 5baa9ebd3e71acecdcc3da31d9042fb174d55a42829f8315f2457080978b1389
    url: https://cran.r-project.org/src/base/R-3/R-3.6.1.tar.gz
build:
    detect_binary_files_with_prefix: true
    ignore_run_exports:
        - libgcc-ng
        - libopenblas
    no_link:
        - lib/R/etc/Makeconf
        - lib/R/etc/javaconf
        - lib/R/etc/ldpaths
        - lib/R/etc/x64/Makeconf
        - lib/R/etc/x64/javaconf
        - lib/R/etc/x64/ldpaths
    number: '1'
    rpaths:
        - lib/
        - lib/R/lib/
    string: h9bb98a2_1
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - autoconf 2.69 pl526hebd4dad_5
        - automake 1.16.1 pl526_0
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - ca-certificates 2019.8.28 0
        - ca-certificates-cos6-x86_64 2016.2.10 h4d6d018_0
        - cairo 1.14.12 h8948797_3
        - fontconfig 2.13.0 h9420a91_0
        - freetype 2.9.1 h8a8886c_1
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - gfortran_impl_linux-64 7.3.0 hdf63c60_1
        - gfortran_linux-64 7.3.0 h553295d_8
        - glib 2.56.2 hd408876_0
        - gmp 6.1.2 h6c8ec71_1
        - graphite2 1.3.13 h23475e2_0
        - gsl 2.4 h14c3975_4
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_8
        - harfbuzz 1.8.8 hffaf4a1_0
        - icu 58.2 h9c2bf20_1
        - java-1.7.0-openjdk-cos6-x86_64 1.7.0.131 h06d78d4_0
        - jpackage-utils-cos6-x86_64 1.7.5 ha353daa_0
        - jpeg 9b h024ee3a_2
        - krb5 1.16.1 h173b8e3_7
        - libcurl 7.65.3 h20c2e04_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libice-cos6-x86_64 1.0.6 hc649955_0
        - libice-devel-cos6-x86_64 1.0.6 h94b5eae_0
        - libjpeg-turbo-cos6-x86_64 1.2.1 h24432d5_0
        - libpng 1.6.37 hbc83047_0
        - libsm-cos6-x86_64 1.2.1 h5e9240c_0
        - libsm-devel-cos6-x86_64 1.2.1 h6ebe058_0
        - libssh2 1.8.2 h1ba5d50_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libtiff 4.0.10 h2733197_2
        - libuuid 1.0.3 h1bed415_2
        - libx11-common-cos6-x86_64 1.6.4 h023ea50_0
        - libx11-cos6-x86_64 1.6.4 h64a1553_0
        - libx11-devel-cos6-x86_64 1.6.4 hb9851ce_0
        - libxau-cos6-x86_64 1.0.6 h4888106_0
        - libxcb 1.13 h1bed415_1
        - libxcb-cos6-x86_64 1.12 h6fd0490_0
        - libxext-cos6-x86_64 1.3.3 hc47956f_0
        - libxml2 2.9.9 hea5a465_1
        - libxrender-cos6-x86_64 0.9.10 h41db5cd_0
        - libxt-cos6-x86_64 1.1.4 hc01df4b_0
        - libxt-devel-cos6-x86_64 1.1.4 hd4125e4_0
        - m4 1.4.18 h4e445db_0
        - make 4.2.1 h1bed415_1
        - mpfr 4.0.1 hdf1c602_3
        - ncurses 6.1 he6710b0_1
        - openjpeg 2.3.0 h05c96fa_1
        - openssl 1.1.1d h7b6447c_2
        - p11-kit-cos6-x86_64 0.18.5 he72ed6d_0
        - p11-kit-trust-cos6-x86_64 0.18.5 h140be7e_0
        - patch 2.7.6 h1bed415_0
        - pcre 8.43 he6710b0_0
        - perl 5.26.2 h14c3975_0
        - pixman 0.38.0 h7b6447c_0
        - pkg-config 0.29.2 h1bed415_8
        - poppler 0.65.0 h581218d_1
        - poppler-data 0.4.9 0
        - texlive-core 20180414 hc8d0b01_0
        - tk 8.6.8 hbc83047_0
        - xorg-x11-proto-devel-cos6-x86_64 7.7 h8d4a98b_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
        - zstd 1.3.7 h0b5b093_0
    host:
        - _libgcc_mutex 0.1 main
        - blas 1.0 openblas
        - bwidget 1.9.11 1
        - bzip2 1.0.8 h7b6447c_0
        - ca-certificates 2019.8.28 0
        - cairo 1.14.12 h8948797_3
        - fontconfig 2.13.0 h9420a91_0
        - freetype 2.9.1 h8a8886c_1
        - fribidi 1.0.5 h7b6447c_0
        - glib 2.56.2 hd408876_0
        - graphite2 1.3.13 h23475e2_0
        - gsl 2.4 h14c3975_4
        - harfbuzz 1.8.8 hffaf4a1_0
        - icu 58.2 h9c2bf20_1
        - jpeg 9b h024ee3a_2
        - krb5 1.16.1 h173b8e3_7
        - libcurl 7.62.0 h20c2e04_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libopenblas 0.3.6 h5a2b251_1
        - libpng 1.6.37 hbc83047_0
        - libssh2 1.8.2 h1ba5d50_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libtiff 4.0.10 h2733197_2
        - libuuid 1.0.3 h1bed415_2
        - libxcb 1.13 h1bed415_1
        - libxml2 2.9.9 hea5a465_1
        - ncurses 6.1 he6710b0_1
        - nomkl 3.0 0
        - openblas 0.3.6 1
        - openblas-devel 0.3.6 1
        - openssl 1.1.1d h7b6447c_2
        - pango 1.42.4 h049681c_0
        - pcre 8.43 he6710b0_0
        - pixman 0.38.0 h7b6447c_0
        - readline 7.0 h7b6447c_5
        - tk 8.6.8 hbc83047_0
        - tktable 2.10 h14c3975_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
        - zstd 1.3.7 h0b5b093_0
    run:
        - _r-mutex 1.* anacondar_1
        - bwidget
        - bzip2 >=1.0.8,<2.0a0
        - cairo >=1.14.12,<2.0a0
        - curl
        - freetype >=2.9.1,<3.0a0
        - gcc_linux-64
        - gfortran_linux-64
        - glib >=2.56.2,<2.57.0a0
        - gsl >=2.4,<2.5.0a0
        - gxx_linux-64
        - icu >=58.2,<59.0a0
        - jpeg >=9b,<10a
        - krb5 >=1.16.1,<1.17.0a0
        - libcurl >=7.62.0,<8.0a0
        - libgcc-ng >=7.3.0
        - libgfortran-ng >=7,<8.0a0
        - libpng >=1.6.37,<1.7.0a0
        - libssh2 >=1.8.2,<2.0a0
        - libstdcxx-ng >=7.3.0
        - libtiff >=4.0.10,<5.0a0
        - libuuid >=1.0.3,<2.0a0
        - libxml2 >=2.9.9,<2.10.0a0
        - make
        - ncurses >=6.1,<7.0a0
        - pango >=1.42.4,<2.0a0
        - pcre >=8.43,<9.0a0
        - readline >=7.0,<8.0a0
        - tk >=8.6.8,<8.7.0a0
        - tktable
        - xz >=5.2.4,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - R -h
        - R --version
        - R -e "library('tcltk')"
        - Rscript --version
        - Rscript -e  'cat("ok\\n")'
        - Rscript test-svg.R
        - Rscript -e "stopifnot(capabilities('jpeg'), TRUE)"
        - Rscript -e "stopifnot(capabilities('png'), TRUE)"
    files:
        - test-svg.R
about:
    home: http://www.r-project.org/
    license: GPL-3.0
    license_family: GPL
    license_file:
        - COPYING
        - dependency_licenses/lapack-netlib.txt
        - dependency_licenses/openblas.txt
    summary: R is a free software environment for statistical computing and graphics.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bgruening
        - isuruf
        - jdblischak
        - johanneskoester
        - ktietz
        - mingwandroid
        - ocefpaf
        - sodre
