# This file created by conda-build 3.10.7
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/gsl-2.4-on-linux_64, last modified Mon Jun 11 15:52:56 2018
# ------------------------------------------------

package:
    name: gsl
    version: '2.4'
source:
    patches:
        - bessel_test.diff
    sha256: 4d46d07b946e7b31c19bbf33dda6204d7bedc2f5462a1bae1d4013426cd1ce9b
    url: http://ftp.gnu.org/gnu/gsl/gsl-2.4.tar.gz
build:
    number: '4'
    run_exports:
        - gsl >=2.4,<2.5.0a0
    string: h14c3975_4
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 7.2.0 had2808c_27
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 h550dcbe_27
        - libstdcxx-ng 7.2.0 hdf63c60_3
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
    run:
        - libgcc-ng >=7.2.0
test:
    commands:
        - gsl-config --prefix
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    home: http://www.gnu.org/software/gsl/
    license: GPL-3.0
    license_file: COPYING
    summary: GNU Scientific Library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - kwilcox
        - mingwandroid
        - ocefpaf
