# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pcre-8.43-on-linux_64, last modified Tue Mar 12 07:42:59 2019
# ------------------------------------------------

package:
    name: pcre
    version: '8.43'
source:
    fn: pcre-8.43.tar.gz
    patches:
        - 0001-Define-snprintf-for-old-VS.patch
        - 0002-Workaround-CMake-FIND_PACKAGE-ZLIB-looking-on-PATH-misfeature.patch
    sha256: 0b8e7465dc5e98c757cc3650a20a7843ee4c3edf50aaf60bb33fd879690d2c73
    url: ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.43.tar.gz
build:
    number: '0'
    run_exports:
        - pcre >=8.43,<9.0a0
    string: he6710b0_0
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_6
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_6
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_6
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - libtool 2.4.6 h7b6447c_5
        - make 4.2.1 h1bed415_1
        - pkg-config 0.29.2 h1bed415_8
    host:
        - bzip2 1.0.6 h14c3975_5
        - ca-certificates 2019.1.23 0
        - cmake 3.12.2 h52cb24c_0
        - expat 2.2.6 he6710b0_0
        - krb5 1.16.1 h173b8e3_7
        - libcurl 7.64.0 h20c2e04_2
        - libedit 3.1.20181209 hc058e9b_0
        - libgcc-ng 8.2.0 hdf63c60_1
        - libssh2 1.8.0 h1ba5d50_4
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1b h7b6447c_1
        - rhash 1.3.7 h1ba5d50_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
test:
    commands:
        - pcre-config --version
        - pcregrep --help
        - pcretest --help
        - test -f "${PREFIX}/include/pcre.h"
        - test -f "${PREFIX}/include/pcre_scanner.h"
        - test -f "${PREFIX}/include/pcre_stringpiece.h"
        - test -f "${PREFIX}/include/pcrecpp.h"
        - test -f "${PREFIX}/include/pcrecpparg.h"
        - test -f "${PREFIX}/include/pcreposix.h"
        - test -f "${PREFIX}/lib/libpcre.a"
        - test -f "${PREFIX}/lib/libpcre.so"
        - test -f "${PREFIX}/lib/libpcrecpp.a"
        - test -f "${PREFIX}/lib/libpcrecpp.so"
        - test -f "${PREFIX}/lib/libpcreposix.a"
        - test -f "${PREFIX}/lib/libpcreposix.so"
about:
    description: 'PCRE implement regular expression pattern matching using the same
        syntax and

        semantics as Perl 5. PCRE has its own native API, as well as a set of wrapper

        functions that correspond to the POSIX regular expression API.

        '
    dev_url: http://vcs.pcre.org/pcre2/
    doc_source_url: https://vcs.pcre.org/pcre2/code/trunk/doc/?sortdir=down
    doc_url: http://www.pcre.org/original/doc/html/
    home: http://www.pcre.org/
    license: BSD 3-Clause
    license_family: BSD
    summary: Regular expression pattern matching using the same syntax and semantics
        as Perl 5.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - scopatz
        - sebastian-luna-valero
