# This file created by conda-build 3.17.3
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/libarchive-3.3.3-on-linux_canary, last modified Wed Dec 12 18:03:20 2018
# ------------------------------------------------

package:
    name: libarchive
    version: 3.3.3
source:
    fn: libarchive-3.3.3.tar.gz
    patches:
        - 0001-Add-lib-to-CMAKE_FIND_LIBRARY_PREFIXES-for-lzma.patch
        - 0002-xar-fix-bad-seek-in-move_reading_point.patch
        - 0003-VC9-compatibility-test-for-BCryptDeriveKeyPBKDF2.patch
        - 0004-VC9-compatibility-define-BCRYPT_SUCCESS.patch
        - 0006-VC-openssl-define-inline-as-__inline.patch
        - 0007-CMake-VC9-compatibility-ignore-some-warnings.patch
        - 0008-VC9-compatibility-remove-C99.patch
        - 0009-CMake-Force-Multi-threaded-DLL-runtime.patch
        - 0010-Use-CreateSymbolicLinkW-on-Windows-for-symlinks-WIP.patch
    sha256: 720da414e7aebb255fcdaee106894e4d30e2472ac1390c2c15b70c84c7479658
    url: https://github.com/libarchive/libarchive/archive/v3.3.3.tar.gz
build:
    number: '5'
    string: h5d8350f_5
requirements:
    build:
        - autoconf 2.69 pl526hebd4dad_5
        - automake 1.16.1 pl526_0
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - libtool 2.4.6 h7b6447c_5
        - m4 1.4.18 h4e445db_0
        - make 4.2.1 h1bed415_1
        - perl 5.26.2 h14c3975_0
        - pkg-config 0.29.2 h1bed415_8
    host:
        - bzip2 1.0.6 h14c3975_5
        - ca-certificates 2018.03.07 0
        - icu 58.2 h9c2bf20_1
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - libxml2 2.9.8 h26e45fe_1
        - lz4-c 1.8.1.2 h14c3975_0
        - lzo 2.10 h49e0be7_2
        - openssl 1.1.1a h7b6447c_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
        - zstd 1.3.7 h0b5b093_0
    run:
        - bzip2 >=1.0.6,<2.0a0
        - libgcc-ng >=7.3.0
        - libxml2 >=2.9.8,<2.10.0a0
        - lz4-c >=1.8.1.2,<1.9.0a0
        - lzo >=2.10,<3.0a0
        - openssl >=1.1.1a,<1.1.2a
        - xz >=5.2.4,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zstd >=1.3.7,<1.3.8.0a0
test:
    commands:
        - test -f "${PREFIX}/lib/pkgconfig/libarchive.pc"
        - test -f "${PREFIX}/include/archive.h"
        - test -f "${PREFIX}/include/archive_entry.h"
        - test -f "${PREFIX}/lib/libarchive.a"
        - test -f "${PREFIX}/lib/libarchive.so"
        - bsdcat --version
        - bsdcpio --version
        - bsdtar --version
        - bsdtar -tf test/hello_world.xar
    files:
        - test/hello_world.xar
about:
    home: http://www.libarchive.org/
    license: BSD 2-Clause
    summary: Multi-format archive and compression library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
