# This file created by conda-build 3.18.10
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/glib-2.63.1-python_3.6-on-linux_64, last modified Tue Nov  5 18:48:50 2019
# ------------------------------------------------

package:
    name: glib
    version: 2.63.1
source:
    patches:
        - patches/0001-replace-hardcoded-paths.patch
        - patches/0002-skip-fileutils-tests.patch
        - patches/0003-add-install_rpath-to-meson-build-files.patch
    sha256: 6bd00b8e410501f0fb76078b970b8d1bcb290507f1c02288dee2b3a75c2fa082
    url: http://ftp.gnome.org/pub/GNOME/sources/glib/2.63/glib-2.63.1.tar.xz
build:
    number: '0'
    run_exports:
        - glib >=2.63.1,<3.0a0
    string: h5a9c865_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - ca-certificates 2019.10.16 0
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_8
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - ninja 1.9.0 py37hfd86e86_0
        - openssl 1.1.1d h7b6447c_3
        - pkg-config 0.29.2 h1bed415_8
        - python 3.7.5 h0371630_0
        - readline 7.0 h7b6447c_5
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.10.16 0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - meson 0.52.0 py_0
        - ncurses 6.1 he6710b0_1
        - ninja 1.9.0 py36hfd86e86_0
        - openssl 1.1.1d h7b6447c_3
        - pcre 8.43 he6710b0_0
        - python 3.6.9 h265db76_0
        - readline 7.0 h7b6447c_5
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - libffi >=3.2.1,<4.0a0
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - pcre >=8.43,<9.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -f ${PREFIX}/lib/libglib-2.0.so
        - test ! -f ${PREFIX}/lib/libgobject-2.0.la
        - gapplication help
        - gdbus help
        - gio version
        - gio-querymodules .
        - glib-compile-resources --help
        - glib-compile-schemas --help
        - gobject-query --help
        - gresource help
        - gtester --help
about:
    description: 'GLib provides the core application building blocks for libraries
        and

        applications written in C. It provides the core object system used in

        GNOME, the main loop implementation, and a large set of utility functions

        functions for strings and common data structures.

        '
    dev_url: https://git.gnome.org/browse/glib/
    doc_source_url: https://git.gnome.org/browse/glib/tree/docs
    doc_url: https://developer.gnome.org/glib/unstable/
    home: https://developer.gnome.org/glib/
    license: LGPL-2.1
    license_file: COPYING
    summary: Provides core application building blocks for libraries and applications
        written in C.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - jakirkham
        - ocefpaf
        - pkgw
        - scopatz
