# This file created by conda-build 3.18.7
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/conda-package-handling-1.3.11-python_3.7-on-linux_canary, last modified Thu Jul 11 13:47:39 2019
# ------------------------------------------------

package:
    name: conda-package-handling
    version: 1.3.11
source:
    fn: conda-package-handling-1.3.11.tar.gz
    sha256: 92d3f1d68d0d084adcc9ed6b1a8ea04753bf273c206fe1eea0816f3c493611e9
    url: https://github.com/conda/conda-package-handling/releases/download/1.3.11/conda-package-handling-1.3.11.tar.gz
build:
    entry_points:
        - cph = conda_package_handling.cli:main
    number: '0'
    script: /tmp/build/80754af9/conda-package-handling_1562853222775/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
        -m pip install . --no-deps -vv
    string: py37_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.5.15 0
        - certifi 2019.6.16 py37_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1c h7b6447c_1
        - pip 19.1.1 py37_0
        - python 3.7.3 h0371630_0
        - readline 7.0 h7b6447c_5
        - setuptools 41.0.1 py37_0
        - sqlite 3.28.0 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.4 py37_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - libarchive >=3.3.3
        - python >=3.7,<3.8.0a0
        - python-libarchive-c
        - six
        - tqdm
test:
    commands:
        - pytest tests
    requires:
        - mock
        - pytest
        - pytest-cov
        - pytest-mock
    source_files:
        - tests
about:
    home: https://github.com/conda/conda-package-handling
    license: BSD-3-Clause
    license_family: BSD
    summary: Create and extract conda packages of various formats
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
