# This file created by conda-build 3.8.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/make-4.2.1-on-linux_64, last modified Wed Apr  4 18:44:44 2018
# ------------------------------------------------

package:
    name: make
    version: 4.2.1
source:
    fn: make-4.2.1.tar.bz2
    sha256: d6e262bf3601b42d2b1e4ef8310029e1dcf20083c5446b4b7aa67081fdffc589
    url: https://ftp.gnu.org/gnu/make/make-4.2.1.tar.bz2
build:
    detect_binary_files_with_prefix: 'False'
    number: '1'
    string: h1bed415_1
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 7.2.0 26
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 26
        - libstdcxx-ng 7.2.0 hdf63c60_3
    run:
        - libgcc-ng >=7.2.0
test:
    command:
        - $PREFIX/bin/make --help
about:
    doc_url: https://www.gnu.org/software/make/manual/
    home: https://www.gnu.org/software/make/
    license: GPLv3
    summary: GNU Make is a tool which controls the generation of executables and other
        non-source files of a program from the program's source files.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - asmeurer
        - scopatz
