# This file created by conda-build 3.2.2
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/tktable-2.10-on-linux_64, last modified Tue Jan 16 12:22:12 2018
# ------------------------------------------------

package:
    name: tktable
    version: '2.10'
source:
    sha256: c335117fa1be45fe4d3032e96fd4b4641fff6a4f8467878608dabed11198a4cb
    url: http://downloads.sourceforge.net/project/tktable/tktable/2.10/Tktable2.10.tar.gz
build:
    number: '0'
    string: h14c3975_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 25
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 25
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - libx11-common-cos6-x86_64 1.6.4 h023ea50_0
        - libx11-cos6-x86_64 1.6.4 h64a1553_0
        - libx11-devel-cos6-x86_64 1.6.4 hb9851ce_0
        - libxau-cos6-x86_64 1.0.6 h4888106_0
        - libxcb-cos6-x86_64 1.12 h6fd0490_0
        - xorg-x11-proto-devel-cos6-x86_64 7.7 h8d4a98b_0
    host:
        - libgcc-ng 7.2.0 h7cc24e2_2
        - tk 8.6.7 hc745277_3
    run:
        - libgcc-ng >=7.2.0
        - tk
        - tk >=8.6.7,<8.7.0a0
test:
    commands:
        - echo "if {[catch {package require -exact Tktable 2.10; exit 0}]} {exit 1}"
            | xvfb-run tclsh
about:
    doc_url: https://core.tcl.tk/jenglish/gutter/packages/tktable.html
    home: http://www.tcl.tk/
    license: Tcl/Tk
    license_family: BSD
    summary: Tktable is a 2D editable table widget
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mingwandroid
