# This file created by conda-build 3.13.0
# ------------------------------------------------

package:
    name: gcc_impl_linux-64
    version: 7.3.0
source:
    path: .
build:
    binary_relocation:
        - bin/*
        - lib/*.so*
        - libexec/**/*.so*
        - libexec/**/cc1*
        - libexec/**/collect2
        - libexec/**/gcc
        - libexec/**/lto*
        - libexec/**/plugin/gengtype
    detect_binary_files_with_prefix: false
    missing_dso_whitelist:
        - '*'
    number: 1
    runpath_whitelist:
        - x86_64-conda_cos6-linux-gnu/sysroot/lib/libpthread-2.12.2.so
    string: habb00fd_1
requirements:
    run:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
test:
    commands:
        - CC=$(${PREFIX}/bin/*-gcc -dumpmachine)-gcc
        - ${CC} -Wall tests/aligned_alloc.c -o c_aligned
        - ./c_aligned
    files:
        - tests
about:
    home: https://gcc.gnu.org/
    license: GPL
    summary: GNU C Compiler
extra:
    copy_test_source_files: true
    final: true
