# This file created by conda-build 3.0.30
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/lzo-2.10-on-linux_64, last modified Thu Nov 16 04:09:11 2017
# ------------------------------------------------

package:
    name: lzo
    version: '2.10'
source:
    sha256: c0f892943208266f9b6543b3ae308fab6284c5c90e627931446fb49b4221a072
    url: http://www.oberhumer.com/opensource/lzo/download/lzo-2.10.tar.gz
build:
    number: '2'
    run_exports:
        - lzo >=2.10,<3.0a0
    string: h49e0be7_2
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 hc67e822_14
        - bzip2 1.0.6 h6d464ef_2
        - ca-certificates 2017.08.26 h1d4fec5_0
        - cmake 3.9.4 h142f0e9_0
        - curl 7.55.1 h78862de_4
        - expat 2.2.5 he0dffb1_0
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 hf1c97a4_14
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libssh2 1.8.0 h8c220ad_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - libuv 1.14.0 h56b52c2_0
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2m h26d622b_1
        - rhash 1.3.5 hbf7ad62_1
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - libgcc-ng 7.2.0.*
test:
    commands:
        - test -f ${PREFIX}/include/lzo/lzoconf.h
        - test -f ${PREFIX}/lib/liblzo2.a
        - test -f ${PREFIX}/lib/liblzo2.so
        - conda inspect linkages -p $PREFIX lzo
about:
    description: 'LZO offers pretty fast compression and extremely fast decompression.

        MiniLZO is a very lightweight subset of the LZO library.

        '
    home: http://www.oberhumer.com/opensource/lzo/
    license: GPL v2+
    license_family: GPL2
    license_file: COPYING
    summary: LZO is a portable lossless data compression library written in ANSI C.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - rmax
