# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/ca-certificates-2019.5.15-on-linux_canary, last modified Mon Jun  3 14:33:15 2019
# ------------------------------------------------

package:
    name: ca-certificates
    version: 2019.5.15
source:
    fn: cacert.pem
    sha256: cb2eca3fbfa232c9e3874e3852d43b33589f27face98eef10242a853d83a437a
    url: https://curl.haxx.se/ca/cacert-2019-05-15.pem
build:
    commands:
        - /usr/bin/curl --cacert "${PREFIX}/ssl/cacert.pem" https://www.google.com
        - /usr/bin/openssl -CAfile "${PREFIX}/ssl/cacert.pem" -CApath nosuchdir s_client
            -showcerts -connect www.google.com:443
        - test -f "${PREFIX}/ssl/cacert.pem"
        - test -f "${PREFIX}/ssl/cert.pem"
    string: '0'
about:
    home: https://github.com/conda-forge/ca-certificates-feedstock
    license: ISC
    summary: Certificates for use with other packages.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
