# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/libssh2-1.9.0-on-linux_64, last modified Mon Mar  9 17:50:51 2020
# ------------------------------------------------

package:
    name: libssh2
    version: 1.9.0
source:
    patches:
        - 0001-libssh2-1.9.0-CVE-2019-17498.patch
    sha256: d5fb8bd563305fd1074dda90bd053fb2d29fc4bce048d182f96eaa466dfadafd
    url: https://www.libssh2.org/download/libssh2-1.9.0.tar.gz
build:
    number: '1'
    run_exports:
        - libssh2 >=1.9.0,<2.0a0
    string: h1ba5d50_1
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - cmake-binary 3.9.1 h2f8e2a0_1
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - make 4.2.1 h1bed415_1
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - libgcc-ng 9.1.0 hdf63c60_0
        - openssl 1.1.1d h7b6447c_4
    run:
        - libgcc-ng >=7.3.0
        - openssl >=1.1.1d,<1.1.2a
test:
    commands:
        - test -f $PREFIX/include/libssh2.h
        - test -f $PREFIX/include/libssh2_publickey.h
        - test -f $PREFIX/include/libssh2_sftp.h
        - test -f $PREFIX/lib/libssh2.a
        - test -f $PREFIX/lib/libssh2${SHLIB_EXT}
about:
    description: 'libssh2 is a library implementing the SSH2 protocol, available under
        the revised BSD license.

        '
    dev_url: https://github.com/libssh2/libssh2
    home: https://www.libssh2.org/
    license: BSD-3-Clause
    license_family: BSD
    license_file: COPYING
    summary: the SSH library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - shadowwalkersb
