[frontends.frontend__2F]
backend = "backend__2F"
passHostHeader = true

[frontends.frontend__2Fuser_2Fbio-admin_2F]
backend = "backend__2Fuser_2Fbio-admin_2F"
passHostHeader = true

[frontends.frontend__2F.routes.test]
rule = "PathPrefix:/"
data = "{\"hub\": true}"

[frontends.frontend__2Fuser_2Fbio-admin_2F.routes.test]
rule = "PathPrefix:/user/bio-admin/"
data = "{\"user\": \"bio-admin\", \"server_name\": \"\"}"

[backends.backend__2F.servers.server1]
url = "http://127.0.0.1:15001"
weight = 1

[backends.backend__2Fuser_2Fbio-admin_2F.servers.server1]
url = "http://127.0.0.1:45615"
weight = 1
