# This file created by conda-build 3.10.9+36.gd10dbde.dirty
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/freetype-feedstock/recipe, last modified Tue Aug  7 10:05:34 2018
# ------------------------------------------------

package:
    name: freetype
    version: 2.9.1
source:
    fn: freetype-2.9.1.tar.bz2
    patches:
        - 0001-Unbreak-CMake-Windows-installation.patch
        - 0002-Win-Specify-RUNTIME-destination-for-dll.patch
    sha256: db8d87ea720ea9d5edc5388fc7a0497bb11ba9fe972245e0f7f4c7e8b1e1e84d
    url: http://download.savannah.gnu.org/releases/freetype/freetype-2.9.1.tar.bz2
build:
    number: '1'
    run_exports:
        - freetype >=2.9.1,<3.0a0
    string: h8a8886c_1
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - make 4.2.1 h1bed415_1
    host:
        - libgcc-ng 8.2.0 hdf63c60_1
        - libpng 1.6.34 hb9fc6fc_0
        - zlib 1.2.11 ha838bed_2
    run:
        - libgcc-ng >=7.3.0
        - libpng >=1.6.34,<1.7.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - ${PREFIX}/bin/freetype-config --version
about:
    description: 'FreeType is designed to be small, efficient, highly customizable

        and portable while capable of producing high-quality output (glyph images)

        of most vector and bitmap font formats.

        '
    dev_url: http://git.savannah.gnu.org/cgit/freetype/
    doc_source_url: https://sourceforge.net/projects/freetype/?source=navbar
    doc_url: http://freetype.sourceforge.net/freetype2/documentation.html
    home: https://www.freetype.org/
    license: GPL-2.0 and FreeType
    license_url: http://freetype.sourceforge.net/FTL.TXT
    summary: A Free, High-Quality, and Portable Font Engine
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - msarahan
        - ocefpaf
