# This file created by conda-build 3.16.2
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/zstd-1.3.7-on-linux_64, last modified Mon Nov  5 20:19:01 2018
# ------------------------------------------------

package:
    name: zstd
    version: 1.3.7
source:
    patches:
        - patches/0005-CMake-Fix-windres-.rc-not-including-programs-windres.patch
    sha256: 3277f236df0ca6edae01ae84e865470000c5a3484588fd5bc3d869877fd3573d
    url: https://github.com/facebook/zstd/releases/download/v1.3.7/zstd-1.3.7.tar.gz
build:
    number: '0'
    run_exports:
        - zstd >=1.3.7,<1.3.8.0a0
    string: h0b5b093_0
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - bzip2 1.0.6 h14c3975_5
        - ca-certificates 2018.03.07 0
        - cmake 3.12.2 h52cb24c_0
        - expat 2.2.6 he6710b0_0
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_3
        - libcurl 7.62.0 h20c2e04_0
        - libgcc-ng 8.2.0 hdf63c60_1
        - libssh2 1.8.0 h1ba5d50_4
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - make 4.2.1 h1bed415_1
        - ncurses 6.1 hf484d3e_0
        - openssl 1.1.1 h7b6447c_0
        - rhash 1.3.6 h1ba5d50_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 ha838bed_2
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.10.15 py37_0
        - libedit 3.1.20170329 h6b74fdf_2
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - lz4 2.1.2 py37h7b6447c_0
        - lz4-c 1.8.1.2 h14c3975_0
        - ncurses 6.1 hf484d3e_0
        - openssl 1.1.1 h7b6447c_0
        - python 3.7.1 h0371630_3
        - readline 7.0 h7b6447c_5
        - setuptools 40.5.0 py37_0
        - sqlite 3.25.2 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 ha838bed_2
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - xz >=5.2.4,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - zstd -be -i5
        - test -f ${PREFIX}/include/zstd.h
        - test -f ${PREFIX}/lib/libzstd.a
        - test -f ${PREFIX}/lib/libzstd.so
        - pkg-config --cflags libzstd
    requires:
        - pkg-config
about:
    description: 'Zstandard is a real-time compression algorithm, providing high compression

        ratios. It offers a very wide range of compression / speed trade-off, while

        being backed by a very fast decoder. It also offers a special mode for

        small data, called dictionary compression, and can create dictionaries from

        any sample set. Zstandard library is provided as open source software using

        a BSD license.

        '
    dev_url: https://github.com/facebook/zstd
    doc_url: https://facebook.github.io/zstd/zstd_manual.html
    home: http://www.zstd.net
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Zstandard - Fast real-time compression algorithm
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - rmax
