# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/wheel-0.33.4-python_3.7-on-linux_canary, last modified Tue May 14 17:28:10 2019
# ------------------------------------------------

package:
    name: wheel
    version: 0.33.4
source:
    sha256: 62fcfa03d45b5b722539ccbc07b190e4bfff4bb9e3a4d470dd9f6a0981002565
    url: https://pypi.io/packages/source/w/wheel/wheel-0.33.4.tar.gz
build:
    entry_points:
        - wheel = wheel.cli:main
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2019.3.9 py37_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1b h7b6447c_1
        - python 3.7.3 h0371630_0
        - readline 7.0 h7b6447c_5
        - setuptools 41.0.1 py37_0
        - sqlite 3.28.0 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.7,<3.8.0a0
        - setuptools
test:
    commands:
        - wheel --help
    imports:
        - wheel
about:
    home: https://github.com/pypa/wheel
    license: MIT
    license_file: LICENSE.txt
    summary: A built-package format for Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - ocefpaf
        - pelson
