# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/certifi-2019.6.16-python_3.7-on-linux_64, last modified Thu Jun 20 22:40:16 2019
# ------------------------------------------------

package:
    name: certifi
    version: 2019.6.16
source:
    sha256: 945e3ba63a0b9f577b1395204e13c3a231f9bc0223888be653286534e5873695
    url: https://pypi.io/packages/source/c/certifi/certifi-2019.6.16.tar.gz
build:
    number: '0'
    preserve_egg_dir: true
    script: python setup.py install
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.5.15 0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1c h7b6447c_1
        - python 3.7.3 h0371630_0
        - readline 7.0 h7b6447c_5
        - sqlite 3.28.0 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - certifi
about:
    description: 'Certifi is a curated collection of Root Certificates for validating
        the

        trustworthiness of SSL certificates while verifying the identity of TLS

        hosts.

        '
    dev_url: https://github.com/certifi/python-certifi
    doc_source_url: https://github.com/certifi/certifi.io/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/certifi
    home: http://certifi.io/
    license: ISC
    license_file: LICENSE
    summary: Python package for providing Mozilla's CA Bundle.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - ocefpaf
        - pelson
        - sigmavirus24
