# This file created by conda-build 3.17.8+291.g7efcb8d.dirty
# meta.yaml template originally from:
# /home/builder/ktietz/aggregateR/r-lattice-feedstock/recipe, last modified Fri May 17 03:53:07 2019
# ------------------------------------------------

package:
    name: r-lattice
    version: '0.20_38'
source:
    sha256: fdeb5e3e50dbbd9d3c5e2fa3eef865132b3eef30fbe53a10c24c7b7dfe5c0a2d
    url:
        - https://cran.r-project.org/src/contrib/Archive/lattice/lattice_0.20-38.tar.gz
        - https://cran.r-project.org/src/contrib/lattice_0.20-38.tar.gz
build:
    number: '0'
    rpaths:
        - lib/
        - lib/R/lib/
    string: r36h96ca727_0
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_7
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_7
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - make 4.2.1 h1bed415_1
    host:
        - _r-mutex 1.0.0 anacondar_1
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 7.2.0 had2808c_27
        - bwidget 1.9.11 1
        - bzip2 1.0.6 h14c3975_5
        - ca-certificates 2019.1.23 0
        - cairo 1.14.12 h8948797_3
        - curl 7.64.1 hbc83047_0
        - fontconfig 2.13.0 h9420a91_0
        - freetype 2.9.1 h8a8886c_1
        - fribidi 1.0.5 h7b6447c_0
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 h550dcbe_27
        - gfortran_impl_linux-64 7.2.0 hdf63c60_3
        - gfortran_linux-64 7.2.0 h550dcbe_27
        - glib 2.56.2 hd408876_0
        - graphite2 1.3.13 h23475e2_0
        - gxx_impl_linux-64 7.2.0 hdf63c60_3
        - gxx_linux-64 7.2.0 h550dcbe_27
        - harfbuzz 1.8.8 hffaf4a1_0
        - icu 58.2 h9c2bf20_1
        - jpeg 9b h024ee3a_2
        - krb5 1.16.1 h173b8e3_7
        - libcurl 7.64.1 h20c2e04_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 8.2.0 hdf63c60_1
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libpng 1.6.37 hbc83047_0
        - libssh2 1.8.2 h1ba5d50_0
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - libtiff 4.0.10 h2733197_2
        - libuuid 1.0.3 h1bed415_2
        - libxcb 1.13 h1bed415_1
        - libxml2 2.9.9 he19cac6_0
        - make 4.2.1 h1bed415_1
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1b h7b6447c_1
        - pango 1.42.4 h049681c_0
        - pcre 8.43 he6710b0_0
        - pixman 0.38.0 h7b6447c_0
        - r-base 3.6.0 hce969dd_0
        - readline 7.0 h7b6447c_5
        - tk 8.6.8 hbc83047_0
        - tktable 2.10 h14c3975_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
        - zstd 1.3.7 h0b5b093_0
    run:
        - libgcc-ng >=7.3.0
        - r-base >=3.6,<3.7.0a0
test:
    commands:
        - $R -e "library('lattice')"
about:
    home: http://lattice.r-forge.r-project.org/
    license: GPL (>= 2)
    license_family: GPL3
    license_file: /home/builder/ktietz/conda/conda-bld/r-lattice_1558085618950/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/R/share/licenses/GPL-2
    summary: A powerful and elegant high-level data visualization system inspired
        by Trellis graphics, with an emphasis on multivariate data. Lattice is sufficient
        for typical graphics needs, and is also flexible enough to handle most nonstandard
        requirements. See ?Lattice for an introduction.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mingwandroid
        - ocefpaf
