# This file created by conda-build 3.10.3
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/cairo-1.14.12-on-linux_64, last modified Fri May 25 11:35:19 2018
# ------------------------------------------------

package:
    name: cairo
    version: 1.14.12
source:
    sha1: 490025a0ba0622a853010f49fb6343f29fb70b9b
    url: http://cairographics.org/releases/cairo-1.14.12.tar.xz
build:
    number: '3'
    run_exports:
        - cairo >=1.14.12,<2.0a0
    string: h8948797_3
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 7.2.0 had2808c_27
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 h550dcbe_27
        - gxx_impl_linux-64 7.2.0 hdf63c60_3
        - gxx_linux-64 7.2.0 h550dcbe_27
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - libtool 2.4.6 h544aabb_3
        - libx11-common-cos6-x86_64 1.6.4 h023ea50_0
        - libx11-cos6-x86_64 1.6.4 h64a1553_0
        - libx11-devel-cos6-x86_64 1.6.4 hb9851ce_0
        - libxau-cos6-x86_64 1.0.6 h4888106_0
        - libxau-devel-cos6-x86_64 1.0.6 hf5ff492_0
        - libxext-cos6-x86_64 1.3.3 hc47956f_0
        - libxext-devel-cos6-x86_64 1.3.3 hf6a4bb0_0
        - libxrender-cos6-x86_64 0.9.10 h41db5cd_0
        - libxrender-devel-cos6-x86_64 0.9.10 ha8151bf_0
        - make 4.2.1 h1bed415_1
        - pkg-config 0.29.2 h1bed415_8
        - xorg-x11-proto-devel-cos6-x86_64 7.7 h8d4a98b_0
    host:
        - fontconfig 2.13.0 h9420a91_0
        - freetype 2.9.1 h8a8886c_0
        - glib 2.56.1 h000015b_0
        - icu 58.2 h9c2bf20_1
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 hdf63c60_3
        - libpng 1.6.34 hb9fc6fc_0
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - libuuid 1.0.3 h1bed415_2
        - libxcb 1.13 h1bed415_1
        - libxml2 2.9.8 h26e45fe_1
        - pcre 8.42 h439df22_0
        - pixman 0.34.0 hceecf20_3
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 ha838bed_2
    run:
        - fontconfig >=2.13.0,<3.0a0
        - freetype >=2.9.1,<3.0a0
        - glib >=2.56.1,<2.57.0a0
        - icu >=58.2,<59.0a0
        - libgcc-ng >=7.2.0
        - libpng >=1.6.34,<1.7.0a0
        - libstdcxx-ng >=7.2.0
        - libxcb >=1.13,<2.0a0
        - pixman >=0.34.0,<1.0a0
        - xz >=5.2.4,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - cairo-trace --help
        - test -f $PREFIX/lib/libcairo.a
        - test -f $PREFIX/lib/libcairo.so
        - test -f $PREFIX/lib/libcairo-gobject.a
        - test -f $PREFIX/lib/libcairo-gobject.so
        - test -f $PREFIX/lib/libcairo-script-interpreter.a
        - test -f $PREFIX/lib/libcairo-script-interpreter.so
        - conda inspect linkages -p $PREFIX cairo
about:
    description: 'Cairo is a 2D graphics library with support for multiple output
        devices.

        It is designed to produce consistent output on all output media while

        taking advantage of display hardware acceleration when available.

        '
    dev_url: https://cgit.freedesktop.org/cairo/
    doc_source_url: https://cgit.freedesktop.org/cairo/tree/doc
    doc_url: http://cairographics.org/documentation/
    home: http://cairographics.org/
    license: LGPL 2.1 or MPL 1.1
    summary: Cairo is a 2D graphics library with support for multiple output devices.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - jakirkham
        - ocefpaf
        - pkgw
